apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-management-sa
  # namespace: default
  annotations:
    # Fill this in after creating the IAM role (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::938041861431:role/live-auction-auction-management-irsa
